version: '3'

services:
  web:
    build: .
    command: gunicorn core.wsgi:application --bind 0.0.0.0:8000
    volumes:
      - .:/app
    env_file:
      - .env
    depends_on:
      - db
      - redis

  static_files:
    build: .
    command: python manage.py collectstatic --no-input
    volumes:
      - static_files:/app/static/

  db:
    image: postgres:16.2-alpine
    environment:
      POSTGRES_DB: ${DATABASE_NAME}
      POSTGRES_USER: ${DATABASE_USER}
      POSTGRES_PASSWORD: ${DATABASE_PASSWORD}
    volumes:
      - postgres_data:/var/lib/postgresql/data/

  redis:
    image: redis:7.2-alpine

  nginx:
    image: nginx:alpine
    ports:
      - "4000:80"
    volumes:
      - ./nginx/nginx.conf:/etc/nginx/nginx.conf:ro
      # - ./nginx_logs:/var/log/nginx/
      - static_files:/static/
    depends_on:
      - static_files
      - web

volumes:
  postgres_data:
  static_files:
